# 项目相关配置
casic:
  # 名称
  name: Casic706
  # 版本
  version: 1.0.0
  #打印系统  0代表在windows系统部署 1 代表在linux系统部署
  sysVersion: 1
  #部署环境--本机打印系统端口（linux系统）
  printPort: 9000
#开发环境--本机打印系统端口（windows系统）
#  printPort: 888
  # 版权年份
  copyrightYear: 2018
  # 开发环境--文件上传路径
#  profile: D:/profile/
#部署环境--文件上传路径
  profile: \usr\local\bank\profile\
  # 开发环境--文件上传路径
#  downloadFilePath: D:/casic_bank/download/
#部署环境--文件上传路径
  downloadFilePath: \usr\local\bank\download\
  # 获取ip地址开关
  addressEnabled: true
  # 系统编码
  sysCode: 00
  #idm base
  base:
#开发环境--系统路径
#    path: http://localhost/
#部署环境--系统路径
    path: http://localhost/ADBC_SMS

# 开发环境配置
server:
  # 服务端口
  port: 8081
  servlet:
    # 项目contextPath
    #context-path: /
    context-path: /ADBC_SMS
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

# 部署环境配置
#server:
#  # 服务端口
#  port: 8081
#  servlet:
#    # 项目contextPath
#    context-path: /ADBC_SMS


# 日志配置
logging:
  level:
    com.casic: debug
    org.springframework: WARN
    org.spring.springboot.dao: debug

# 用户配置
user:
  password:
    # 密码错误{maxRetryCount}次锁定10分钟
    maxRetryCount: 5

# Spring配置
spring:
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
    prefix: classpath:/templates/
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles: 
    active: druid
  # 文件上传
  servlet:
     multipart:
       max-file-size:  30MB
       max-request-size:  30MB
       enabled: true
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  # 事务配置  
  transaction:
    rollback-on-commit-failure: true
  liquibase:
    enabled: false
  mvc:
    favicon:
      enabled: false
# MyBatis
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.casic,org.casic
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath:mapper/system/*Mapper.xml,classpath:mapper/quartz/*Mapper.xml,classpath:mapper/generator/*Mapper.xml,classpath:mapper/auth/*Mapper.xml,classpath:mybatis/mapper/*.xml,classpath:/META-INF/modeler-mybatis-mappings/*.xml,classpath:mapper/bank/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mapper/mybatis-config.xml
    configuration-properties:
      blobType: BLOB
      boolValue: true
      prefix:

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql 

# Shiro
shiro:
  user:
    # 登录地址
    loginUrl: /login
    # 权限认证失败地址
    unauthorizedUrl: /unauth
    # 首页地址
    indexUrl: /index
    # 验证码开关
    captchaEnabled: false
    # 验证码类型 math 数组计算 char 字符
    captchaType: math
  cookie:
    # 设置Cookie的域名 默认空，即当前访问的域名
    domain: 
    # 设置cookie的有效访问路径
    path: /
    # 设置HttpOnly属性
    httpOnly: true
    # 设置Cookie的过期时间，天为单位
    maxAge: 30
  session:
    # Session超时时间（默认30分钟）
    expireTime: 30
    # 同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 1
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 10

# flowable配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: when_authorized
      roles: access-admin
flowable:
  database-schema-update: true
  activityFontName: \u5B8B\u4F53
  labelFontName: \u5B8B\u4F53
  annotationFontName: \u5B8B\u4F53
  common:
    app:
      role-prefix:
      idm-url: ${casic.base.path}/idm
    admin:
      user-id: admin
      password: 111111
      first-name: admin
      last-name: admin
  modeler:
    app:
      rest-enabled: true
  rest:
    app:
      authentication-mode: verify-privilege
  process:
    definition-cache-limit: 1
  xml:
    encoding: UTF-8

# 防止XSS攻击
xss: 
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*,/auth/*

# 代码生成
gen: 
  # 作者
  author: yuzengwen
  # 默认生成包路径 module 需改成自己的模块名称 如 system monitor tool
  packageName: com.casic.module
  # 自动去除表前缀，默认是true
  autoRemovePre: false
  # 表前缀(类名不会包含表前缀)
  tablePrefix: sys_

web:
  copy-path: D:/JavaWork/micro-frame/casic-springcloud/git_system_manage_master/dev_platform/casic-system-manager-sso/casic-oauth2-client-member/src/main/resources
  